package goose

func opRawGetTable(s *State)       {}
func opRawSetTable(s *State)       {}
func opSetTable(s *State)          {}
func opGetTable(s *State)          {}
func opPop(s *State)               {}
func opCall(s *State)              {}
func opLoadValue(s *State)         {}
func opLoadConstInt(s *State)      {}
func opLoadConstBool(s *State)     {}
func opLoadConstNil(s *State)      {}
func opAdd(s *State)               {}
func opSub(s *State)               {}
func opMul(s *State)               {}
func opDiv(s *State)               {}
func opBitwiseXor(s *State)        {}
func opBitwiseOr(s *State)         {}
func opBitwiseAnd(s *State)        {}
func opBitwiseLeftshift(s *State)  {}
func opBitwiseRightshift(s *State) {}
func opLessThan(s *State)          {}
func opGreaterThan(s *State)       {}
func opLessThanEqual(s *State)     {}
func opGreaterThanEqual(s *State)  {}
func opEqual(s *State)             {}
func opNotEqual(s *State)          {}
func opApproxEqual(s *State)       {}
func opIdentical(s *State)         {}
func opJump(s *State)              {}
func opPanic(s *State)             {}
